### ISSUE TITLE
1234556

### ISSUE THREAD

**Issue by secret344** [amiezhang/attendance#1]
学长 我可以参考下吗 我的毕设也是这个唉  我现在就是不知道咋设计 具体的逻辑

**Comment by amiezhang** [comment]
哈哈哈，欢迎欢迎，不过这是我当时边学边写的东西，写得很烂，别介意就好。

**Comment by secret344** [comment]
因为我要做同类型移动端的app 现在问题就是后台。我对数据库现在很不熟悉 前端我倒是没问题 你可以给我看下你之前的数据库吗，我大概就知道我该怎么弄数据了。我个人现在是做前端开发 长时间都是调接口，后台接触很少，但还是有点基础的，软件设计这块讲道理我现在很头大。

**Comment by amiezhang** [comment]
我把数据库生成的脚本添加好了哈，根目录下的attendance.sql

你创建一个数据库，然后执行这个这个文件里的脚本就可以了，不过只有结构没有数据（数据不能给你哈，因为里面有一些同学的信息）

**Comment by secret344** [comment]
谢谢学长了 ，  帮我了大忙。最近对这个数据库设计一直头疼。
